version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    container_name: ticket-db

  api:
    build:
      context: .
    ports:
      - "5000:80"
    depends_on:
      - db
    container_name: ticket-api
